if(typeof XML=="undefined")XML=function(){};XML.ObjTree=function(){return this};XML.ObjTree.VERSION="0.24";XML.ObjTree.prototype.xmlDecl='<?xml version="1.0" encoding="UTF-8" ?>\n';XML.ObjTree.prototype.attr_prefix="-";XML.ObjTree.prototype.overrideMimeType="text/xml";
XML.ObjTree.prototype.parseXML=function(a){var b;if(window.DOMParser){b=new DOMParser;a=b.parseFromString(a,"application/xml");if(!a)return;b=a.documentElement}else if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async=false;b.loadXML(a);b=b.documentElement}if(b)return this.parseDOM(b)};
XML.ObjTree.prototype.parseHTTP=function(a,b,c){var d={},e;for(e in b)d[e]=b[e];if(!d.method)d.method=typeof d.postBody=="undefined"&&typeof d.postbody=="undefined"&&typeof d.parameters=="undefined"?"get":"post";if(c){d.asynchronous=true;var h=this,f=d.onComplete;d.onComplete=function(i){var j;if(i&&i.responseXML&&i.responseXML.documentElement)j=h.parseDOM(i.responseXML.documentElement);else if(i&&i.responseText)j=h.parseXML(i.responseText);c(j,i);f&&f(i)}}else d.asynchronous=false;var g;if(typeof HTTP!=
"undefined"&&HTTP.Request){d.uri=a;if(a=new HTTP.Request(d))g=a.transport}else if(typeof Ajax!="undefined"&&Ajax.Request)if(a=new Ajax.Request(a,d))g=a.transport;if(c)return g;if(g&&g.responseXML&&g.responseXML.documentElement)return this.parseDOM(g.responseXML.documentElement);else if(g&&g.responseText)return this.parseXML(g.responseText)};
XML.ObjTree.prototype.parseDOM=function(a){if(a){this.__force_array={};if(this.force_array)for(var b=0;b<this.force_array.length;b++)this.__force_array[this.force_array[b]]=1;b=this.parseElement(a);if(this.__force_array[a.nodeName])b=[b];if(a.nodeType!=11){var c={};c[a.nodeName]=b;b=c}return b}};
XML.ObjTree.prototype.parseElement=function(a){if(a.nodeType!=7){if(a.nodeType==3||a.nodeType==4){if(a.nodeValue.match(/[^\x00-\x20]/)==null)return;return a.nodeValue}var b,c={};if(a.attributes&&a.attributes.length){b={};for(var d=0;d<a.attributes.length;d++){var e=a.attributes[d].nodeName;if(typeof e=="string"){var h=a.attributes[d].nodeValue;if(h){e=this.attr_prefix+e;if(typeof c[e]=="undefined")c[e]=0;c[e]++;this.addNode(b,e,c[e],h)}}}}if(a.childNodes&&a.childNodes.length){e=true;if(b)e=false;
for(d=0;d<a.childNodes.length&&e;d++){h=a.childNodes[d].nodeType;h==3||h==4||(e=false)}if(e){b||(b="");for(d=0;d<a.childNodes.length;d++)b+=a.childNodes[d].nodeValue}else{b||(b={});for(d=0;d<a.childNodes.length;d++){e=a.childNodes[d].nodeName;if(typeof e=="string")if(h=this.parseElement(a.childNodes[d])){if(typeof c[e]=="undefined")c[e]=0;c[e]++;this.addNode(b,e,c[e],h)}}}}return b}};
XML.ObjTree.prototype.addNode=function(a,b,c,d){if(this.__force_array[b]){if(c==1)a[b]=[];a[b][a[b].length]=d}else if(c==1)a[b]=d;else if(c==2)a[b]=[a[b],d];else a[b][a[b].length]=d};XML.ObjTree.prototype.writeXML=function(a){return this.xmlDecl+this.hash_to_xml(null,a)};
XML.ObjTree.prototype.hash_to_xml=function(a,b){var c=[],d=[],e;for(e in b)if(b.hasOwnProperty(e)){var h=b[e];if(e.charAt(0)!=this.attr_prefix)c[c.length]=typeof h=="undefined"||h==null?"<"+e+" />":typeof h=="object"&&h.constructor==Array?this.array_to_xml(e,h):typeof h=="object"?this.hash_to_xml(e,h):this.scalar_to_xml(e,h);else d[d.length]=" "+e.substring(1)+'="'+this.xml_escape(h)+'"'}d=d.join("");e=c.join("");typeof a=="undefined"||a==null||(e=c.length>0?e.match(/\n/)?"<"+a+d+">\n"+e+"</"+a+">\n":
"<"+a+d+">"+e+"</"+a+">\n":"<"+a+d+" />\n");return e};XML.ObjTree.prototype.array_to_xml=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d];c[c.length]=typeof e=="undefined"||e==null?"<"+a+" />":typeof e=="object"&&e.constructor==Array?this.array_to_xml(a,e):typeof e=="object"?this.hash_to_xml(a,e):this.scalar_to_xml(a,e)}return c.join("")};XML.ObjTree.prototype.scalar_to_xml=function(a,b){return a=="#text"?this.xml_escape(b):"<"+a+">"+this.xml_escape(b)+"</"+a+">\n"};
XML.ObjTree.prototype.xml_escape=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};
var bookData={loaded:false,background:"",load:function(a){var b=new XML.ObjTree;b.attr_prefix="@";a=b.parseDOM(a);a=a["#document"];this.size={};this.size.width=a.Properties.bookProperties.bookWidth?a.Properties.bookProperties.bookWidth["@value"]:600;this.size.height=a.Properties.bookProperties.bookHeight?a.Properties.bookProperties.bookHeight["@value"]:800;bookData.background=a.Properties.bookProperties.bookBG["@src"];this.page={};b=0;for(item in a.Properties.bookProperties.pages.elements.page){b++;
item=a.Properties.bookProperties.pages.elements.page[item];bookData.page[b]={};bookData.page[b].width=item.width?item.isWide&&item.isWide["@value"]=="true"?item.width["@value"]/2:item.width["@value"]:item.isWide&&item.isWide["@value"]=="true"?a.Properties.bookProperties.pages.defaultValue.width["@value"]/2:a.Properties.bookProperties.pages.defaultValue.width["@value"];bookData.page[b].height=item.height?item.height["@value"]:a.Properties.bookProperties.pages.defaultValue.height["@value"];bookData.page[b].proportions=
(bookData.page[b].width/bookData.page[b].height-0.0010).toFixed(2);bookData.page[b].stub=item.isStub?true:false;if(item.isWide&&item.isWide["@value"]=="true"){bookData.page[b+1]={};bookData.page[b+1].height=bookData.page[b].height;bookData.page[b+1].width=bookData.page[b].width;bookData.page[b+1].stub=bookData.page[b].stub;bookData.page[b+1].proportions=bookData.page[b].proportions;bookData.page[b].wide=true;bookData.page[b+1].wide=true;bookData.page[b].src=images.getImagePath(item.id["@value"],true,
1);bookData.page[b+1].src=images.getImagePath(item.id["@value"],true,2);if(item.links){bookData.page[b].links={};this.linksImport(item,b)}b++}else{bookData.page[b].src=images.getImagePath(item.id["@value"]);bookData.page[b].wide=false;if(item.links){bookData.page[b].links={};this.linksImport(item,b)}}}this.pageCount=b;this.size.proportions=(bookData.size.width/bookData.size.height-0.0010).toFixed(2);this.loaded=true},linksImport:function(a,b,c){c=c||"normal";a=a.links.link[0]?a.links.link:[a.links.link];
for(var d=0;d<a.length;d++){bookData.page[b].links[d]=[];if(c=="wide"){bookData.page[b+1].links[d]=[];if(a[d].x["@value"]*1>bookData.size.width*1){bookData.page[b+1].links[d].x=a[d].x["@value"]-bookData.size.width*1;bookData.page[b].links[d].width=a[d].width["@value"]}else if(a[d].x["@value"]*1<bookData.size.width*1&&a[d].x["@value"]*1+a[d].width["@value"]*1>bookData.size.width*1){bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b+1].links[d].x=0;bookData.page[b].links[d].width=a[d].width["@value"]*
1-a[d].x["@value"]*1;bookData.page[b+1].links[d].width=a[d].x["@value"]*1+a[d].width["@value"]*1-bookData.size.width*1}else{bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b].links[d].width=a[d].width["@value"]}bookData.page[b].links[d].y=a[d].y["@value"]}else{bookData.page[b].links[d].x=a[d].x["@value"];bookData.page[b].links[d].y=a[d].y["@value"];bookData.page[b].links[d].width=a[d].width["@value"]}bookData.page[b].links[d].height=a[d].height["@value"];if(a[d].page["@id"])bookData.page[b].links[d].page=
a[d].page["@id"];if(a[d].urls){bookData.page[b].links[d].urls=[];if(a[d].urls.url[0])for(var e=0;e<a[d].urls.url.length;e++)bookData.page[b].links[d].urls[e]=a[d].urls.url[e].src;else bookData.page[b].links[d].urls[0]=a[d].urls.url["@src"]}}}},device={width:function(){return window.innerWidth},height:function(){if(this.name()=="iPhone3G"||this.name()=="iPhone4G")if(window.innerHeight==416&&orientationObserver.getOrientation()=="portrait")return window.innerHeight;else if(window.innerHeight<416&&orientationObserver.getOrientation()==
"portrait")return window.innerHeight+60;else if(window.innerHeight>250&&orientationObserver.getOrientation()=="landscape")return window.innerHeight;else{if(window.innerHeight<250&&orientationObserver.getOrientation()=="landscape")return window.innerHeight+60}else return window.innerHeight},proportions:function(){return(this.width()/this.height()).toFixed(2)},name:function(){var a;a=window.innerWidth<=480&&Browser.Platform.ios&&orientationObserver.getOrientation()=="landscape"?"iPhone3G":"other";a=
window.innerWidth<=320&&Browser.Platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPhone3G":a;a=window.innerWidth<=960&&window.innerWidth>480&&Browser.Platform.ios&&orientationObserver.getOrientation()=="landscape"?"iPhone4G":a;a=window.innerWidth<=640&&window.innerWidth>320&&Browser.Platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPhone4G":a;a=window.innerWidth<=1024&&window.innerWidth>960&&Browser.Platform.ios&&orientationObserver.getOrientation()=="landscape"?"iPad":
a;return a=window.innerWidth<=768&&window.innerWidth>640&&Browser.Platform.ios&&orientationObserver.getOrientation()=="portrait"?"iPad":a}},ua=navigator.userAgent.toLowerCase(),platform=navigator.platform.toLowerCase(),UA=ua.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||[null,"unknown",0],mode=UA[1]=="ie"&&document.documentMode,Browser={extend:Function.prototype.extend,name:UA[1]=="version"?UA[3]:UA[1],version:mode||parseFloat(UA[1]=="opera"&&
UA[4]?UA[4]:UA[2]),Platform:{name:ua.match(/ip(?:ad|od|hone)/)?"ios":(ua.match(/(?:webos|android|bada|symbian|palm|blackberry)/)||platform.match(/mac|win|linux/)||["other"])[0]},Features:{xpath:!!document.evaluate,air:!!window.runtime,query:!!document.querySelector,json:!!window.JSON},Plugins:{}};Browser[Browser.name]=true;Browser[Browser.name+parseInt(Browser.version,10)]=true;Browser.Platform[Browser.Platform.name]=true;
var eventManager={touchInterface:false,leftAndRightArea:0.15,gesture:false,touchStartCoordinate:{x:0,y:0},clickStartCoordinate:{x:0,y:0},click:false,clickCount:0,doubleClickTime:250,start:function(){if("createTouch"in document){eventManager.touchInterface=true;eventManager.loadTouchEvents()}else{eventManager.touchInterface=false;eventManager.loadClickEvents()}},loadTouchEvents:function(){var a=document.getElementById("mainFrame"),b=function(g){g.preventDefault();eventManager.gesture=true;delete b},
c=function(g){g.preventDefault();delete c},d=function(g){g.preventDefault();window.setTimeout(function(){eventManager.gesture=false},10);delete d};a.addEventListener("gesturestart",b);a.addEventListener("gesturechange",c);a.addEventListener("gestureend",d);var e=function(g){pager.state=="input"&&pager.cancelInput();eventManager.touchStartCoordinate.x=g.targetTouches[0].pageX;eventManager.touchStartCoordinate.y=g.targetTouches[0].pageY;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchStart(g);
else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchStart(g);else zoomBook.installed&&zoomBook.events.touchStart(g);g.preventDefault();delete e},h=function(g){if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchMove(g);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchMove(g);else zoomBook.installed&&zoomBook.events.touchMove(g);g.preventDefault();delete h},f=function(g){if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.touchEnd(g);
else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.touchEnd(g);else zoomBook.installed&&zoomBook.events.touchEnd(g);g.preventDefault();delete f};a.addEventListener("touchstart",e);a.addEventListener("touchmove",h);a.addEventListener("touchend",f);delete null},loadClickEvents:function(){var a=function(){event.preventDefault();eventManager.click=true;pager.state=="input"&&pager.cancelInput();eventManager.clickStartCoordinate.x=event.pageX;eventManager.clickStartCoordinate.y=event.pageY;
if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mousedown(event);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.mousedown(event);else zoomBook.installed&&zoomBook.events.mousedown(event);delete a},b=function(){event.preventDefault();eventManager.click=false;if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mouseup(event);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.mouseup(event);else zoomBook.installed&&zoomBook.events.mouseup(event);
delete b},c=function(){event.preventDefault();if(eventManager.click)if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.events.mousemove(event);else if(onePageBook.installed&&!zoomBook.installed)onePageBook.events.mousemove(event);else zoomBook.installed&&zoomBook.events.mousemove(event);delete c},d=document.getElementById("mainFrame");d.addEventListener("mousedown",a);d.addEventListener("mousemove",c);d.addEventListener("mouseup",b);delete null},pagerEvent:function(){document.getElementById("pagerCurrentPage").addEventListener("click",
pager.enableInput)},pagerInputEvent:function(){if(pager.installed&&pager.state=="input"){var a=function(b){if(b.keyCode==13){pager.change();pageMediator.goToPage(b.target.value)}delete a};document.getElementById("inputPage").addEventListener("keydown",a)}},linkClick:function(a,b,c,d){if(eventManager.touchInterface)var e=a.changedTouches[0].pageX-a.target.getBoundingClientRect().left,h=a.changedTouches[0].pageY-a.target.getBoundingClientRect().top;else{e=a.clientX-a.target.getBoundingClientRect().left;
h=a.clientY-a.target.getBoundingClientRect().top}for(linkI in bookData.page[b].links){var f=bookData.page[b].links[linkI];if(e>=f.x*c&&e<=f.x*c+f.width*c&&h>=(f.y*d).toFixed(0)*1&&h<=((f.y*d).toFixed(0)*1+f.height*d).toFixed(0)*1){a.preventDefault();a.stopPropagation();var g=f.x*c,i=f.y*d;if(eventManager.touchInterface){var j=a.target.getContext("2d"),n=j.getImageData(g,i,f.width*c+10,f.height*d+10);j.fillStyle="rgba(0,0,0,0.4)";j.fillRect(f.x*c,f.y*d,f.width*c,f.height*d);(function(k){a.target.addEventListener("touchend",
function(){j.putImageData(n,g,i);k.page&&pageMediator.goToPage(k.page);if(k.urls)for(var l=0;l<k.urls.length;l++)window.open(k.urls[l])})})(f)}else{f.page&&pageMediator.goToPage(f.page);if(f.urls)for(var m=0;m<f.urls.length;m++)window.open(f.urls[m])}}}}},images={image:new Image,imageStack:[],processing:false,getImagePath:function(a,b,c){b=b||false;c=c||0;var d="000"+a;if(a>9)d="00"+a;if(a>99)d="0"+a;if(a>999)d=""+a;if(dir==null)PATH_TO_PROPERTIES=photographer_img;if(device.name()=="iPhone3G")return b?
PATH_TO_PROPERTIES+"page"+d+"_i1_"+c+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+d+"_i1.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()=="iPhone4G")return b?PATH_TO_PROPERTIES+"page"+d+"_i1_"+c+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+d+"_i1.jpg?id="+Math.random().toFixed(5)*1E5;if(device.name()=="iPad")return b?PATH_TO_PROPERTIES+"page"+d+"_i1_"+c+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+d+"_i1.jpg?id="+Math.random().toFixed(5)*
1E5;if(device.name()=="other")return b?PATH_TO_PROPERTIES+"page"+d+"_i2_"+c+".jpg?id="+Math.random().toFixed(5)*1E5:PATH_TO_PROPERTIES+"page"+d+"_i2.jpg?id="+Math.random().toFixed(5)*1E5},init:function(){this.image.onload=this.loadImage},loadImage:function(){var a=this.id;if(el.id("canvas"+a)){preloader.deletePreloader(a*1);var b=el.id("canvas"+a).getContext("2d");if(twoPageBook.installed&&!zoomBook.installed)var c=twoPageBook.bookWidth/2,d=twoPageBook.bookHeight;else if(onePageBook.installed&&!zoomBook.installed){c=
onePageBook.bookWidth;d=onePageBook.bookHeight}else if(zoomBook.installed){c=zoomBook.pageWidth;d=zoomBook.pageHeight}if(bookData.page[a].proportions>=bookData.size.proportions){var e=c,h=(e/bookData.page[a].proportions).toFixed(0);c=(d-h)/2}else{h=d;e=(h*bookData.page[a].proportions).toFixed(0);c=bookData.page[a].wide&&a%2==0?c-e:0}bookData.page[a].proportions>=bookData.size.proportions?b.drawImage(images.image,0,c,e,h):b.drawImage(images.image,c,0,e,h);if(a!=1&&a!=bookData.pageCount&&twoPageBook.installed)images.drawShadow(b,
a);else a==bookData.pageCount&&a%2!=0&&images.drawShadow(b,a)}if(images.imageStack.length>0)images.shiftImage();else images.processing=false},drawShadow:function(a,b){if(b%2==0){var c=a.createLinearGradient(twoPageBook.bookWidth/2-twoPageBook.bookWidth/10,0,twoPageBook.bookWidth/2,0);c.addColorStop(0,"rgba(0,0,0,0.0)");c.addColorStop(0.4,"rgba(0,0,0,0.05)");c.addColorStop(0.8,"rgba(0,0,0,0.20)");c.addColorStop(1,"rgba(0,0,0,0.15)")}else{c=a.createLinearGradient(twoPageBook.bookWidth/20,0,0,0);c.addColorStop(0,
"rgba(0,0,0,0)");c.addColorStop(0.6,"rgba(0,0,0,0.1)");c.addColorStop(0.95,"rgba(0,0,0,0.2)");c.addColorStop(1,"rgba(0,0,0,0.65)")}a.fillStyle=c;if(b%2==0){a.fillRect(twoPageBook.bookWidth/2-twoPageBook.bookWidth/4,0,twoPageBook.bookWidth/4,twoPageBook.bookHeight);a.beginPath();a.moveTo(twoPageBook.bookWidth/2,0);a.lineTo(twoPageBook.bookWidth/2,twoPageBook.bookHeight);a.strokeStyle="rgba(0,0,0,0.1)";a.stroke()}else a.fillRect(0,0,twoPageBook.bookWidth/10,twoPageBook.bookHeight)},shiftImage:function(){if(this.imageStack.length>
0){this.processing=true;var a=this.imageStack.shift();this.image.id=a;this.image.src=bookData.page[a].src+Math.random().toFixed(5)*1E5}},push:function(a){this.imageStack.push(a);this.processing||this.shiftImage()},deleteImageFromStack:function(a){a=images.imageStack.indexOf(a);a!=-1&&images.imageStack.splice(a,1)}},links={currStorage:"",currCanvas:"",currX:0,currY:0,currGoPage:0,isLinkBool:false,currURLs:0,drawRect:function(a){links.clearRect();if(onePageBook.installed)var b=onePageBook.currentPage;
else if(twoPageBook.installed)if(a.target.id=="canvas"+twoPageBook.currentPage.left)b=twoPageBook.currentPage.left;else{if(a.target.id=="canvas"+twoPageBook.currentPage.right)b=twoPageBook.currentPage.right}else if(zoomBook.installed)b=zoomBook.currentPage;var c=a.target.width/bookData.size.width,d=a.target.height/bookData.size.height;if(eventManager.touchInterface)var e=eventManager.touchStartCoordinate.x-a.target.getBoundingClientRect().left,h=eventManager.touchStartCoordinate.y-a.target.getBoundingClientRect().top;
else{e=a.clientX-a.target.getBoundingClientRect().left;h=a.clientY-a.target.getBoundingClientRect().top}for(linkI in bookData.page[b].links){var f=bookData.page[b].links[linkI];links.isLinkBool=false;if(e>=f.x*c&&e<=f.x*c+f.width*c&&h>=(f.y*d).toFixed(0)*1&&h<=((f.y*d).toFixed(0)*1+f.height*d).toFixed(0)*1){links.currX=f.x*c;links.currY=f.y*d;b=a.target.getContext("2d");links.currCanvas=a.target.id;links.currStorage=b.getImageData(links.currX,links.currY,f.width*c+10,f.height*d+10);b.fillStyle="rgba(0,0,0,0.3)";
b.fillRect(f.x*c,f.y*d,f.width*c,f.height*d);links.currGoPage=f.page?f.page:0;links.currURLs=f.urls?f.urls:0;links.isLinkBool=true;break}}},clearRect:function(){if(el.id(links.currCanvas)){el.id(links.currCanvas).getContext("2d").putImageData(links.currStorage,links.currX,links.currY);links.isLinkBool=false}}};if(dir=="./<%=FilesFolderName%>/")dir="files";PATH_TO_PROPERTIES="../assets/mobile/";if(dir==null)PATH_TO_PROPERTIES=photographer_dir;
function startBook(a){if(orientationObserver.getOrientation()==="landscape")device.name()=="iPad"?twoPageBook.draw(a):onePageBook.draw(a);else orientationObserver.getOrientation()==="portrait"?onePageBook.draw(a):twoPageBook.draw(a)}
var loadFunc=function(){preloader.init();bookData.load(this.responseXML);images.init();workspace.draw();toolbar.draw();pager.draw();orientationObserver.start();eventManager.start();startBook(1);if(bookData.background!="image/grey-inner.jpg"&&bookData.background!="image/grey-outer.jpg"&&bookData.background!="image/dark-wood-inner.jpg"&&bookData.background!="image/dark-wood-outer.jpg"&&bookData.background!="image/sky-blue-inner.jpg"&&bookData.background!="image/sky-blue-outer.jpg"){el.id("body").style.backgroundImage=
"url(../assets/"+bookData.background+")";el.id("mainFrame").style.backgroundImage="url(../assets/"+bookData.background+")"}console.log(bookData);window.setTimeout(function(){window.scrollTo(0,1)},10);delete loadFunc},myRequest=new XMLHttpRequest;myRequest.open("GET",PATH_TO_PROPERTIES+"properties.xml");myRequest.onload=loadFunc;myRequest.send();delete myRequest;
var el={id:function(a){return document.getElementById(a)},tag:function(a){return document.getElementsByTagName(a)[0]},tags:function(a){return document.getElementsByTagName(a)},add:function(a){return document.createElement(a)},del:function(a){el.id(a).parentNode.removeChild(el.id(a))},Class:function(){return document.getElementsByClassName(tag)}},onePageBook={currentPage:0,installed:false,nextPageBuffer:2,prevPageBuffer:2,flipSpeed:600,triggerStopTime:700,bookWidth:0,bookHeight:0,bookTop:0,bookLeft:0,
draw:function(a){if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=(device.height()-50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}onePageBook.bookTop=((device.height()-onePageBook.bookHeight)/2).toFixed(0);onePageBook.bookLeft=((device.width()-onePageBook.bookWidth)/2).toFixed(0);if(el.id("bookPortrait"))el.id("bookPortrait");
else{var b=el.add("div");b.id="bookPortrait";b.style.webkitPerspective="3000";b.style.position="absolute";b.style.width=onePageBook.bookWidth+"px";b.style.height=onePageBook.bookHeight+"px";b.style.top=onePageBook.bookTop+"px";b.style.left=onePageBook.bookLeft+"px";b.style.webkitBackfaceVisibility="hidden";b.style.webkitBoxShadow="0px 0px 3px #000";el.id("mainFrame").appendChild(b)}onePageBook.installed=true;onePageBook.currentPage=a;pager.change();for(b=a-onePageBook.prevPageBuffer;b<=a*1+onePageBook.nextPageBuffer;b++)onePageBook.drawPage(b)},
drawPage:function(a){if(a>0&&a<=bookData.pageCount&&!el.id("canvas"+a)){var b=el.add("canvas");b.id="canvas"+a;b.className="canvasBook";b.width=onePageBook.bookWidth;b.height=onePageBook.bookHeight;b.style.position="absolute";b.style.left=a<onePageBook.currentPage?-device.width()+"px":"";b.style.zIndex=bookData.pageCount-a+"";var c=b.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,onePageBook.bookWidth,onePageBook.bookHeight);el.id("bookPortrait").appendChild(b);if(!bookData.page[a].stub){images.push(a);
preloader.add(a)}}},destroyPage:function(a){el.id("canvas"+a)&&el.del("canvas"+a);preloader.deletePreloader(a)},next:function(){if(onePageBook.installed&&onePageBook.currentPage<bookData.pageCount&&timer.check("fx")){onePageBook.slideFxPage(onePageBook.currentPage);if(el.id("bookPortrait").childNodes.length==5){var a=onePageBook.currentPage-onePageBook.prevPageBuffer;images.deleteImageFromStack(a);onePageBook.destroyPage(a);preloader.deletePreloader(a);window.scrollTo(0,1)}onePageBook.currentPage++;
onePageBook.drawPage(onePageBook.currentPage*1+onePageBook.nextPageBuffer*1);pager.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},prev:function(){if(onePageBook.installed&&onePageBook.currentPage>1&&timer.check("fx")){onePageBook.slideFxPage(onePageBook.currentPage-1);if(el.id("bookPortrait").childNodes.length==5){var a=onePageBook.currentPage*1+onePageBook.nextPageBuffer*1;images.deleteImageFromStack(a);onePageBook.destroyPage(a);window.scrollTo(0,1)}onePageBook.currentPage--;
onePageBook.drawPage(onePageBook.currentPage-onePageBook.prevPageBuffer);pager.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},slideFxPage:function(a){if(a<onePageBook.currentPage)var b=onePageBook.bookLeft*2+onePageBook.bookWidth*1;else if(a==onePageBook.currentPage)b=0-(onePageBook.bookLeft*2+onePageBook.bookWidth*1);a=el.id("canvas"+a);a.style.webkitTransitionDuration=onePageBook.flipSpeed+"ms";a.style.webkitTransform=a.style.webkitTransform==""||a.style.webkitTransform==
"translate3d(0px, 0px, 0px)"?"translate3d("+b+"px, 0px,0px)":"translate3d(0px, 0px,0px)"},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=bookData.pageCount;if(a==onePageBook.currentPage)pageMediator.change();else if(a==onePageBook.currentPage*1+1)onePageBook.next();else if(a==onePageBook.currentPage*1-1)onePageBook.prev();else if(a>0&&a<=bookData.pageCount&&timer.check("fx")){if(a*1>onePageBook.currentPage*1)var b=onePageBook.currentPage*1+1,c=onePageBook.currentPage;else c=b=onePageBook.currentPage-
1;var d=el.id("canvas"+b).getContext("2d");d.fillStyle="rgb(255,255,255)";d.fillRect(0,0,onePageBook.bookWidth,onePageBook.bookHeight);preloader.add(b);preloader.setSpecial(b);this.slideFxPage(c);this.currentPage=a;pager.change();var e=function(){onePageBook.destroy();onePageBook.draw(a);window.scrollTo(0,1);delete e};d=null;window.setTimeout(e,onePageBook.flipSpeed);b=c=null}},destroyOtherPages:function(){for(var a=onePageBook.currentPage*1+onePageBook.nextPageBuffer*1,b=onePageBook.currentPage-
onePageBook.prevPageBuffer;b<=a;b++)b!=onePageBook.currentPage&&b>0&&b<=bookData.pageCount&&el.del("canvas"+b)},goToZoom:function(){this.destroyOtherPages();var a=orientationObserver.getOrientation()=="portrait"?screen.height/onePageBook.bookWidth:window.innerWidth/onePageBook.bookWidth,b=el.id("canvas"+onePageBook.currentPage);if(b.style.left||b.style.left=="0px"){b.style.webkitTransitionDuration="0ms";b.style.webkitTransform="translate3d(0px, 0px,0px)";b.style.left="0px"}var c=function(){b.style.webkitTransitionDuration=
zoomBook.zoomIOSpeed+"ms";b.style.webkitTransform="scale3d("+a+","+a+",1)";delete c};window.setTimeout(c,1);var d=function(){onePageBook.installed=false;onePageBook.destroyPage(onePageBook.currentPage);el.del("bookPortrait");zoomBook.draw(onePageBook.currentPage,a);delete d};window.setTimeout(d,zoomBook.zoomIOSpeed+10)},destroy:function(){preloader.stopAll();el.del("bookPortrait");onePageBook.installed=false}};
onePageBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a)},touchMove:function(a){if(links.isLinkBool){var b=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(Math.abs(a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},touchEnd:function(a){if(!zoomBook.installed)if(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX<
-50)onePageBook.events.flipRight();else eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX>50?onePageBook.events.flipLeft():onePageBook.events.touchManger(a)},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{onePageBook.events.tapCount++;if(onePageBook.events.tapCount==1){var c=function(){if(onePageBook.events.tapCount==1){onePageBook.events.singleTap(a);onePageBook.events.tapCount=
0}delete c};window.setTimeout(c,onePageBook.events.doubleTapTime)}else{onePageBook.events.doubleTap(a);onePageBook.events.tapCount=0}}},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete null},mouseup:function(){if(!zoomBook.installed)if(eventManager.clickStartCoordinate.x-event.pageX<-50)onePageBook.events.flipRight();else eventManager.clickStartCoordinate.x-event.pageX>50?onePageBook.events.flipLeft():onePageBook.events.clickManger(event)},mousemove:function(a){if(links.isLinkBool){var b=
a.pageY-eventManager.clickStartCoordinate.y;if(Math.abs(a.pageX-eventManager.clickStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{onePageBook.events.clickCount++;if(onePageBook.events.clickCount==1){var c=function(){if(onePageBook.events.clickCount==1){onePageBook.events.singleClick(a);onePageBook.events.clickCount=
0}delete c};window.setTimeout(c,onePageBook.events.doubleClickTime)}else{onePageBook.events.doubleClick(a);onePageBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&onePageBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*onePageBook.events.leftAndRightArea)onePageBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*onePageBook.events.leftAndRightArea?onePageBook.next():toolbar.toogle();delete a},
doubleTap:function(){links.isLinkBool&&links.clearRect();onePageBook.goToZoom()},singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&onePageBook.goToPage(links.currGoPage);if(links.currURLs)for(a=0;a<links.currURLs.length;a++)window.open(links.currURLs[a])}else{if(a.x<device.width()*onePageBook.events.leftAndRightArea)onePageBook.prev();else a.x>device.width()-device.width()*onePageBook.events.leftAndRightArea?onePageBook.next():toolbar.toogle();delete a}},doubleClick:function(){links.isLinkBool&&
links.clearRect();onePageBook.goToZoom()},flipLeft:function(){onePageBook.next()},flipRight:function(){onePageBook.prev()}};
var orientationObserver={start:function(){window.addEventListener("orientationchange",workspace.reDraw,false);var a=function(){if(device.name()=="iPad")if(orientationObserver.getOrientation()=="portrait"){if(twoPageBook.installed){twoPageBook.destroy();onePageBook.draw(twoPageBook.currentPage.right)}}else{if(orientationObserver.getOrientation()=="landscape")if(onePageBook.installed){onePageBook.destroy();twoPageBook.draw(onePageBook.currentPage)}}else if(onePageBook.installed){onePageBook.destroy();
onePageBook.draw(onePageBook.currentPage)}delete a};window.addEventListener("orientationchange",a,false)},stop:function(){window.removeEventListener("orientationchange",workspace.reDraw,false)},getOrientation:function(){if(Math.abs(window.orientation)===0||Math.abs(window.orientation)===180)return"portrait";if(Math.abs(window.orientation)===90)return"landscape"}},pageMediator={next:function(){if(onePageBook.installed&&!zoomBook.installed)onePageBook.next();else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.next();
else zoomBook.installed&&zoomBook.next()},prev:function(){if(onePageBook.installed&&!zoomBook.installed)onePageBook.prev();else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.prev();else zoomBook.installed&&zoomBook.prev()},change:function(){pager.change();twoPageBook.installed&&twoPageBook.shadow.reDraw()},goToPage:function(a){if(onePageBook.installed&&!zoomBook.installed)onePageBook.goToPage(a);else if(twoPageBook.installed&&!zoomBook.installed)twoPageBook.goToPage(a);else zoomBook.installed&&
zoomBook.goToPage(a)}},pager={installed:false,state:"show",draw:function(){if(toolbar.installed){var a=toolbar.toolbarHeight/100*40,b=(toolbar.toolbarHeight-(a+4))/2;if(!pager.installed){var c=el.add("span");c.style.cssFloat="left";c.style.margin=b+"px 0 0 "+b+"px";c.style.color="white";c.style.fontSize=a+"px";c.style.padding="0px";c.style.fontFamily="Helvetica Neue, HelveticaNeue, Helvetica-Neue, Helvetica, BBAlpha Sans, sans-serif";c.style.textShadow="rgba(0, 0, 0, 0.496094) 0px -0.08em 0px";var d=
document.createTextNode("Page  ");c.appendChild(d);el.id("topToolbar").appendChild(c);d=el.add("span");d.id="pagerCurrentPage";d.style.margin=b+"px 0 0 0";d.style.color="white";d.style.fontSize=a+"px";d.style.fontFamily="Helvetica Neue, HelveticaNeue, Helvetica-Neue, Helvetica, BBAlpha Sans, sans-serif";d.style.textShadow="rgba(0, 0, 0, 0.496094) 0px -0.08em 0px";d.innerHTML="0";c.appendChild(d);d=document.createTextNode(" of "+bookData.pageCount);c.appendChild(d)}pager.installed=true;eventManager.pagerEvent()}},
change:function(){pager.state=="input"&&pager.cancelInput();if(onePageBook.installed&&!zoomBook.installed){var a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(onePageBook.currentPage);a.appendChild(nTe)}else if(twoPageBook.installed&&!zoomBook.installed)if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.right<=bookData.pageCount){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.left+"-"+twoPageBook.currentPage.right);
a.appendChild(nTe)}else if(twoPageBook.currentPage.left<=0){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.right);a.appendChild(nTe)}else{if(twoPageBook.currentPage.right>bookData.pageCount){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(twoPageBook.currentPage.left);a.appendChild(nTe)}}else if(zoomBook.installed){a=el.id("pagerCurrentPage");a.removeChild(a.childNodes[0]);nTe=document.createTextNode(zoomBook.currentPage);
a.appendChild(nTe)}},enableInput:function(a){a.preventDefault();pager.state="input";var b=el.add("input");b.id="inputPage";b.type="number";b.style.height=toolbar.toolbarHeight/100*40+"px";b.style.width=toolbar.toolbarHeight/100*120+"px";b.style.verticalAlign="text-top";b.style.padding="0px";b.style.border="1px solid white";b.style.textAlign="center";var c=el.id("pagerCurrentPage");c.parentNode.replaceChild(b,c);b.focus();eventManager.pagerInputEvent();a.preventDefault()},cancelInput:function(){var a=
toolbar.toolbarHeight/100*40,b=(toolbar.toolbarHeight-(a+4))/2,c=el.add("span");c.id="pagerCurrentPage";c.style.margin=b+"px 0 0 0";c.style.color="white";c.style.fontSize=a+"px";if(onePageBook.installed)a=onePageBook.currentPage;else if(twoPageBook.installed){a="";if(twoPageBook.currentPage.left>0&&twoPageBook.currentPage.left<=bookData.pageCount)a=a+twoPageBook.currentPage.left+"-";if(twoPageBook.currentPage.right>0&&twoPageBook.currentPage.right<=bookData.pageCount)a+=twoPageBook.currentPage.right}else a=
zoomBook.installed?zoomBook.currentPage:"0";a=document.createTextNode(a);c.appendChild(a);c.addEventListener("click",pager.enableInput);a=el.id("inputPage");a.parentNode.replaceChild(c,a);pager.state="show"}},preloader={image:new Image,interval:null,preloadersStack:[],imageLoad:false,angle:0,special:0,init:function(){this.image.src=dir==null?photographer_src+"progress.png":"styles/progress.png";this.image.onload=function(){preloader.imageLoad=true;if(preloader.preloadersStack.length>0){for(var a=
0;a<preloader.preloadersStack.length;a++)preloader.draw(el.id("canvas"+preloader.preloadersStack[a]));preloader.startInterval()}}},draw:function(a){var b=a.getContext("2d");b.save();b.translate(a.width/2,a.height/2);b.drawImage(preloader.image,-20,-20,40,40);b.restore()},add:function(a){if(el.id("canvas"+a)){preloader.imageLoad&&preloader.draw(el.id("canvas"+a));this.preloadersStack.push(a);preloader.preloadersStack.length==1&&preloader.imageLoad&&preloader.startInterval()}},setSpecial:function(a){preloader.special=
a},startInterval:function(){clearInterval(preloader.interval);var a=function(){preloader.preloadersStack.length==0&&preloader.stopInterval();preloader.angle+=6;if(preloader.angle==360)preloader.angle=0;if(onePageBook.installed){var b={};b.l=onePageBook.currentPage;b.r=onePageBook.currentPage}else if(twoPageBook.installed){b={};b.l=twoPageBook.currentPage.left;b.r=twoPageBook.currentPage.right}else if(zoomBook.installed){b={};b.l=zoomBook.currentPage;b.r=zoomBook.currentPage}for(var c=0;c<preloader.preloadersStack.length;c++)if(preloader.preloadersStack[c]==
b.l||preloader.preloadersStack[c]==b.r||preloader.preloadersStack[c]==preloader.special){var d=el.id("canvas"+preloader.preloadersStack[c]),e=d.getContext("2d");e.save();e.translate(d.width/2,d.height/2);e.rotate(preloader.angle*(Math.PI/180));e.fillStyle="rgb(255,255,255)";e.fillRect(-30,-30,60,60);e.drawImage(preloader.image,-20,-20,40,40);e.restore()}delete a};preloader.interval=window.setInterval(a,45)},deletePreloader:function(a){a=preloader.preloadersStack.indexOf(a);if(a!=-1){preloader.preloadersStack.splice(a,
1);preloader.preloadersStack.length==0&&preloader.stopInterval()}},stopInterval:function(){clearInterval(preloader.interval)},stopAll:function(){preloader.preloadersStack=[]}};
timer={state:true,blockTime:0,endFX:0,startTime:Date.now(),setBlockTime:function(a,b){this.endFX=b||a;this.blockTime=a;this.startTime=Date.now()},check:function(a){a=a||"standart";if(a=="standart")return Date.now()-this.startTime>this.blockTime?true:false;else if(a=="high")return true;else if(a=="fx")return Date.now()-this.startTime>this.endFX?true:false}};
var toolbar={toolbarHeight:40,status:"hide",installed:false,draw:function(){if(!el.id("topToolbar")){var a=el.add("div");a.className="topToolbar";a.id="topToolbar";a.style.height=toolbar.toolbarHeight+"px";a.style.top="-"+toolbar.toolbarHeight-2+"px";el.id("body").appendChild(a)}if(!el.id("bottomToolbar")){a=el.add("div");a.className="bottomToolbar";a.id="bottomToolbar";a.style.height=toolbar.toolbarHeight+"px";a.style.bottom="-"+toolbar.toolbarHeight-2+"px";var b=dir==null?photographer_src:"styles/",
c=el.add("img");c.src=b+"arrowRight.png";c.style.height=toolbar.toolbarHeight*0.75+"px";c.style.margin=toolbar.toolbarHeight*0.125+"px 15px 0 0";c.style.cursor="pointer";c.style.cssFloat="right";c.addEventListener("click",pageMediator.next);a.appendChild(c);c=el.add("img");c.src=b+"arrowLeft.png";c.style.height=toolbar.toolbarHeight*0.75+"px";c.style.margin=toolbar.toolbarHeight*0.125+"px 15px 0 0";c.style.cursor="pointer";c.style.cssFloat="right";c.addEventListener("click",pageMediator.prev);a.appendChild(c);
el.id("body").appendChild(a)}toolbar.setToolbarHeight();toolbar.installed=true},setToolbarHeight:function(){toolbar.toolbarHeight=40},toogle:function(){pager.state=="input"&&pager.cancelInput();if(this.status=="show"){var a=-toolbar.toolbarHeight-2;toolbar.status="hide"}else{a=toolbar.toolbarHeight+2;toolbar.status="show"}el.id("topToolbar").style.webkitTransformStyle="flat";el.id("topToolbar").style.webkitTransition="0.3s";el.id("topToolbar").style.webkitTransform="translateY("+a+"px)";el.id("bottomToolbar").style.webkitTransformStyle=
"flat";el.id("bottomToolbar").style.webkitTransition="0.3s";el.id("bottomToolbar").style.webkitTransform="translateY("+-a+"px)"}},twoPageBook={currentPage:{left:0,right:0},installed:false,nextPageBuffer:2,prevPageBuffer:2,flipSpeed:800,triggerStopTime:850,bookWidth:0,bookHeight:0,bookTop:0,bookLeft:0,pageConverter:function(a){if(a%2!=0){twoPageBook.currentPage.left=a-1;twoPageBook.currentPage.right=a}else{twoPageBook.currentPage.left=a;twoPageBook.currentPage.right=a*1+1}twoPageBook.currentPage.left*=
1;twoPageBook.currentPage.right*=1},draw:function(a){twoPageBook.pageConverter(a);if(bookData.size.proportions*2<device.proportions()){twoPageBook.bookWidth=((device.height()-150)*bookData.size.proportions*2).toFixed(0);twoPageBook.bookHeight=(device.height()-150).toFixed(0)}else{twoPageBook.bookWidth=device.width()-150;twoPageBook.bookHeight=((device.width()-150)/(bookData.size.proportions*2)).toFixed(0)}twoPageBook.bookTop=((device.height()-twoPageBook.bookHeight)/2).toFixed(0);twoPageBook.bookLeft=
((device.width()-twoPageBook.bookWidth)/2).toFixed(0);if(el.id("bookLandscape"))a=el.id("bookLandscape");else{a=el.add("div");a.id="bookLandscape";a.style.webkitPerspective="3000";a.style.position="absolute";a.style.width=twoPageBook.bookWidth+"px";a.style.height=twoPageBook.bookHeight+"px";a.style.top=twoPageBook.bookTop+"px";a.style.left=twoPageBook.bookLeft+"px";a.style.webkitBackfaceVisibility="hidden";el.id("mainFrame").appendChild(a)}twoPageBook.installed=true;for(var b=twoPageBook.currentPage.left*
1;b>twoPageBook.currentPage.left-twoPageBook.prevPageBuffer*2;b-=2)twoPageBook.drawPage(b,a,"left");for(b=twoPageBook.currentPage.right*1;b<twoPageBook.currentPage.right*1+twoPageBook.nextPageBuffer*2;b+=2)twoPageBook.drawPage(b,a,"right");pager.change();twoPageBook.shadow.draw();delete a},drawPage:function(a,b,c){if(c=="left")var d=a-1+"x"+a,e=a-1,h="rotate3d(0, -1, 0, 0deg)",f=a;else if(c=="right"){d=a+"x"+(a*1+1);e=a*1+1;h="rotate3d(0, 1, 0, 0deg)";f=bookData.pageCount-a}if(!el.id(d)){if(a>0&&
a<=bookData.pageCount){var g=el.add("div");g.id=d;g.style.position="absolute";g.style.cssFloat=c;if(c=="right")g.style.left=twoPageBook.bookWidth/2+"px";g.style.width=twoPageBook.bookWidth/2+"px";g.style.height=twoPageBook.bookHeight+"px";g.style.webkitTransformStyle="preserve-3d";g.style.webkitTransition="-webkit-transform 1s";g.style.webkitTransform=h;g.style.zIndex=f+"";b.appendChild(g);twoPageBook.drawCanvasPage(a,g,"front")}e>0&&e<=bookData.pageCount&&twoPageBook.drawCanvasPage(e,g,"back");delete b}},
drawCanvasPage:function(a,b,c){var d=el.add("canvas");d.id="canvas"+a;d.className="canvasBook";d.width=twoPageBook.bookWidth/2;d.height=twoPageBook.bookHeight;d.style.position="absolute";d.style.webkitBackfaceVisibility="hidden";d.style.webkitTransform=c=="front"?"":"rotateY(180deg)";c=d.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);a==1||a==bookData.pageCount&&a%2==0||images.drawShadow(c,a);b.appendChild(d);if(!bookData.page[a].stub){images.push(a);
preloader.add(a)}},next:function(){if(twoPageBook.installed&&twoPageBook.currentPage.right<bookData.pageCount&&timer.check("fx")){twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.right);if(el.id("bookLandscape").childNodes.length==4){var a=twoPageBook.currentPage.left*1-(twoPageBook.nextPageBuffer*2-1),b=twoPageBook.currentPage.right-(twoPageBook.nextPageBuffer*2-1);images.deleteImageFromStack(a);images.deleteImageFromStack(b);el.del(a+"x"+b);preloader.deletePreloader(a);preloader.deletePreloader(b)}twoPageBook.currentPage.left+=
2;twoPageBook.currentPage.right+=2;a=twoPageBook.currentPage.left*1+(twoPageBook.nextPageBuffer+1);el.id(a)||twoPageBook.drawPage(a,el.id("bookLandscape"),"right");pageMediator.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},prev:function(){if(twoPageBook.installed&&twoPageBook.currentPage.left>0&&timer.check("fx")){twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.left);if(el.id("bookLandscape").childNodes.length==4){var a=twoPageBook.currentPage.left*1+(twoPageBook.prevPageBuffer*
2-1),b=twoPageBook.currentPage.right*1+(twoPageBook.prevPageBuffer*2-1);images.deleteImageFromStack(a);images.deleteImageFromStack(b);el.del(twoPageBook.currentPage.left*1+(twoPageBook.prevPageBuffer*2-1)+"x"+(twoPageBook.currentPage.right+(twoPageBook.prevPageBuffer*2-1)));preloader.deletePreloader(a);preloader.deletePreloader(b)}twoPageBook.currentPage.left-=2;twoPageBook.currentPage.right-=2;a=twoPageBook.currentPage.left*1-twoPageBook.prevPageBuffer;el.id(a)||twoPageBook.drawPage(a,el.id("bookLandscape"),
"left");pageMediator.change();timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=bookData.pageCount;if(a==twoPageBook.currentPage.left||a==twoPageBook.currentPage.right)pageMediator.change();else if(a==twoPageBook.currentPage.right*1+1||a==twoPageBook.currentPage.right*1+2)twoPageBook.next();else if(a==twoPageBook.currentPage.left*1-1||a==twoPageBook.currentPage.left*1-2)twoPageBook.prev();else if(a>0&&a<=bookData.pageCount&&
timer.check("fx")){if(a>twoPageBook.currentPage.right){if(a==bookData.pageCount&&a%2==0){for(var b=1,c=(twoPageBook.nextPageBuffer-1)*2;b<c;b+=2){var d=twoPageBook.currentPage.right*1+b*1+1+"x"+(twoPageBook.currentPage.right*1+b*1+2);el.del(d);d=null}c=el.id("canvas"+(twoPageBook.currentPage.right*1+1));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);c=null;preloader.add(twoPageBook.currentPage.right*1+1);preloader.setSpecial(twoPageBook.currentPage.right*
1+1)}else for(b=1;b<=2;b++){c=el.id("canvas"+(twoPageBook.currentPage.right*1+b));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);images.drawShadow(c,twoPageBook.currentPage.right*1+b);c=null;preloader.add(twoPageBook.currentPage.right*1+b);preloader.setSpecial(twoPageBook.currentPage.right*1+b)}twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.right);twoPageBook.pageConverter(a);pageMediator.change()}else if(a<twoPageBook.currentPage.left){if(a==
1){b=1;for(c=(twoPageBook.prevPageBuffer-1)*2;b<c;b+=2){d=twoPageBook.currentPage.left*1-(b*1+2)+"x"+(twoPageBook.currentPage.left*1-(b*1+1));el.del(d);d=null}c=el.id("canvas"+(twoPageBook.currentPage.left*1-1));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);preloader.add(twoPageBook.currentPage.left*1-1);preloader.setSpecial(twoPageBook.currentPage.left*1-1);c=c=null}else for(b=1;b<=2;b++){c=el.id("canvas"+(twoPageBook.currentPage.left-
b));c=c.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,twoPageBook.bookWidth/2,twoPageBook.bookHeight);images.drawShadow(c,twoPageBook.currentPage.left-b);preloader.add(twoPageBook.currentPage.left-b);preloader.setSpecial(twoPageBook.currentPage.left-b);c=c=null}twoPageBook.flipFxCurrentPage(twoPageBook.currentPage.left);twoPageBook.pageConverter(a);pageMediator.change()}window.setTimeout(function(){preloader.stopAll();el.del("bookLandscape");twoPageBook.draw(a)},twoPageBook.flipSpeed+
100);timer.setBlockTime(twoPageBook.flipSpeed/2,twoPageBook.flipSpeed)}},flipFxCurrentPage:function(a){if(a%2!=0&&twoPageBook.installed&&twoPageBook.currentPage.right<bookData.pageCount){var b=el.id(this.currentPage.right+"x"+(this.currentPage.right*1+1));if(b.style.webkitTransform=="rotate3d(0, 1, 0, 0deg)"||b.style.webkitTransform=="rotate3d(0, -1, 0, 0deg)")var c=a==bookData.pageCount-1?"rotate3d(0, -1, 0, 179."+(1E4-a)+"deg)":"rotate3d(0, -1, 0, 179."+(1E4-a)+"deg)",d="0% 0%";else{c="rotate3d(0, -1, 0, 0deg)";
d="100% 100%"}var e=twoPageBook.currentPage.right*1+1}else if(twoPageBook.installed&&twoPageBook.currentPage.left>0){b=el.id(this.currentPage.left-1+"x"+this.currentPage.left);if(b.style.webkitTransform=="rotate3d(0, -1, 0, 0deg)"||b.style.webkitTransform=="rotate3d(0, 1, 0, 0deg)"){c="rotate3d(0, 1, 0, 179."+(1E4-(bookData.pageCount-a))+"deg)";d="100% 100%"}else{c="rotate3d(0, 1, 0, 0deg)";d="0% 0%"}e=bookData.pageCount-this.currentPage.left}b.style.webkitTransform=c+"";b.style.webkitTransformOrigin=
d+"";b.style.webkitTransitionTimingFunction="cubic-bezier(0, 0, 1, 0.95)";b.style.webkitTransitionDuration=this.flipSpeed+"ms";var h=function(){b.style.zIndex=e+"";delete b;e=c=d=b=null;delete h};window.setTimeout(h,twoPageBook.flipSpeed/2);a=null},destroy:function(){preloader.stopAll();el.del("bookLandscape");twoPageBook.installed=false},goToZoom:function(a){var b=a.target.id;if(b=="canvas"+twoPageBook.currentPage.left)var c=twoPageBook.currentPage.left,d=0,e=twoPageBook.bookWidth/4;else if(b=="canvas"+
twoPageBook.currentPage.right){c=twoPageBook.currentPage.right;d=twoPageBook.bookWidth/2;e=-(twoPageBook.bookWidth/4)}var h=window.innerWidth/(twoPageBook.bookWidth/2),f=a.target;f.style.left=d+"px";el.id("bookLandscape").appendChild(f);if(f.style.webkitTransform=="rotateY(180deg)")f.style.webkitTransform="rotateY(0deg)";var g=function(){f.style.webkitTransitionDuration=zoomBook.zoomIOSpeed+"ms";f.style.webkitTransform="translate3d("+e+"px, 0px, 1px) scale3d("+h+","+h+",1)";delete g};window.setTimeout(g,
1);var i=function(){twoPageBook.installed=false;twoPageBook.destroy();zoomBook.draw(c,h,twoPageBook.bookWidth/2,twoPageBook.bookHeight);b=c=d=e=null;delete i};window.setTimeout(i,zoomBook.zoomIOSpeed+10)}};
twoPageBook.shadow={shadowSize:3,draw:function(){if(twoPageBook.currentPage.right==1){if(el.id("3x4"))el.id("3x4").style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"}else if(twoPageBook.currentPage.left==bookData.pageCount){var a=bookData.pageCount-3+"x"+(bookData.pageCount-2);if(el.id(a))el.id(a).style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"}else if(el.id("bookLandscape"))el.id("bookLandscape").style.webkitBoxShadow="0px 0px "+this.shadowSize+"px #000"},erase:function(){if(el.id("3x4"))el.id("3x4").style.webkitBoxShadow=
"0px 0px 0px #000";var a=bookData.pageCount-3+"x"+(bookData.pageCount-2);if(el.id(a))el.id(a).style.webkitBoxShadow="0px 0px 0px #000";if(el.id("bookLandscape"))el.id("bookLandscape").style.webkitBoxShadow="0px 0px 0px #000"},reDraw:function(){if(twoPageBook.currentPage.left==2||twoPageBook.currentPage.left==bookData.pageCount-2)window.setTimeout(function(){twoPageBook.shadow.erase();twoPageBook.shadow.draw()},twoPageBook.flipSpeed);else if(twoPageBook.currentPage.right==1||twoPageBook.currentPage.left==
bookData.pageCount){this.erase();this.draw()}}};
twoPageBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},touchMove:function(a){if(links.isLinkBool){var b=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(Math.abs(a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},touchEnd:function(a){if(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX<-50)twoPageBook.events.flipRight();
else eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX>50?twoPageBook.events.flipLeft():twoPageBook.events.touchManger(a);delete a},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},mousemove:function(a){if(links.isLinkBool){var b=a.pageY-eventManager.clickStartCoordinate.y;if(Math.abs(a.pageX-eventManager.clickStartCoordinate.x)>10||Math.abs(b)>10)links.clearRect()}delete a},mouseup:function(a){if(eventManager.clickStartCoordinate.x-a.pageX<-50)twoPageBook.events.flipRight();
else eventManager.clickStartCoordinate.x-a.pageX>50?twoPageBook.events.flipLeft():twoPageBook.events.clickManger(a);delete a},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{twoPageBook.events.tapCount++;if(twoPageBook.events.tapCount==1){var c=function(){if(twoPageBook.events.tapCount==1){twoPageBook.events.singleTap(a);twoPageBook.events.tapCount=0}delete c};window.setTimeout(c,
twoPageBook.events.doubleTapTime)}else{twoPageBook.events.doubleTap(a);twoPageBook.events.tapCount=0}}},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{twoPageBook.events.clickCount++;if(twoPageBook.events.clickCount==1){var c=function(){if(twoPageBook.events.clickCount==1){twoPageBook.events.singleClick(a);twoPageBook.events.clickCount=0}delete c};window.setTimeout(c,twoPageBook.events.doubleClickTime)}else{twoPageBook.events.doubleClick(a);
twoPageBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&twoPageBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*twoPageBook.events.leftAndRightArea)twoPageBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*twoPageBook.events.leftAndRightArea?twoPageBook.next():toolbar.toogle();delete a},doubleTap:function(a){links.isLinkBool&&links.clearRect();a.target.tagName=="CANVAS"&&twoPageBook.goToZoom(a)},
singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&twoPageBook.goToPage(links.currGoPage)}else{if(a.x<device.width()*twoPageBook.events.leftAndRightArea)twoPageBook.prev();else a.x>device.width()-device.width()*twoPageBook.events.leftAndRightArea?twoPageBook.next():toolbar.toogle();delete a;a=null}delete a},doubleClick:function(a){links.isLinkBool&&links.clearRect();a.target.tagName=="CANVAS"&&twoPageBook.goToZoom(a)},flipLeft:function(){twoPageBook.next()},flipRight:function(){twoPageBook.prev()}};
var workspace={draw:function(){var a=device.width()+"px",b=device.height()+"px";el.id("mainFrame").style.width=a;el.id("mainFrame").style.height=b;el.id("body").style.width=a;el.id("body").style.height=b},reDraw:function(){workspace.draw()}},zoomBook={currentPage:0,installed:false,verticalScroll:false,horizontalScroll:false,pageAreaWidth:0,pageAreaHeight:0,pageWidth:0,pageHeight:0,topShift:0,leftShift:0,translateScrollX:0,translateScrollY:0,zoomFactor:0,currentPage:0,nextPageBuffer:1,prevPageBuffer:1,
slideSpeed:800,zoomIOSpeed:800,sourcePageHeight:0,sourcePageWidth:0,initSizes:function(a,b,c,d){this.zoomFactor=a;this.currentPage=d;this.pageWidth=b;this.pageHeight=c;this.pageAreaWidth=b>device.width()?b:device.width();this.pageAreaHeight=c>device.height()?c:device.height();this.pageAreaWidth=this.pageAreaWidth;this.translateScrollY=((this.pageAreaHeight-device.height())/2).toFixed(0);this.translateScrollX=((this.pageAreaWidth-device.width())/2).toFixed(0);this.topShift=((device.height()-c)/2).toFixed(0);
this.leftShift=((device.width()-b)/2).toFixed(0);if(b.toFixed(0)>=device.width()){this.horizontalScroll=true;this.leftShift=0}else{this.horizontalScroll=false;this.translateScrollX=0}if(c.toFixed(0)>device.height()){this.verticalScroll=true;this.topShift=0}else{this.verticalScroll=false;this.translateScrollY=0}this.translateX=this.pageAreaWidth*(this.currentPage-1)+this.translateScrollX*1},draw:function(a,b,c,d){b=b||this.zoomFactor;if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=
(device.height()-50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}this.sourcePageWidth=c||onePageBook.bookWidth;this.sourcePageHeight=d||onePageBook.bookHeight;pageWidth=this.sourcePageWidth*b;pageHeight=this.sourcePageHeight*b;this.initSizes(b,pageWidth,pageHeight,a);if(!el.id("zoomBook")){b=el.add("div");b.id="zoomBook";
b.style.webkitPerspective="3000";b.style.position="absolute";b.style.width=this.pageAreaWidth+"px";b.style.height=this.pageAreaHeight+"px";b.style.webkitBackfaceVisibility="hidden";b.style.webkitTransform="translate3d("+-(this.translateScrollX*1)+"px,"+-this.translateScrollY+"px,0px)";el.id("mainFrame").appendChild(b)}zoomBook.installed=true;pager.change();for(b=a-zoomBook.prevPageBuffer;b<=a*1+zoomBook.nextPageBuffer;b++)zoomBook.drawPage(b)},drawPage:function(a){if(a>0&&a<=bookData.pageCount){var b=
el.add("canvas");b.id="canvas"+a;b.className="canvasZoom";b.width=zoomBook.pageWidth;b.height=zoomBook.pageHeight;b.style.left=zoomBook.leftShift+"px";b.style.position="absolute";b.style.webkitBackfaceVisibility="hidden";b.style.webkitTransform="translate3d("+(a-zoomBook.currentPage)*zoomBook.pageAreaWidth+"px, 0px, 0px)";var c=b.getContext("2d");c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);el.id("zoomBook").appendChild(b);if(!bookData.page[a].stub){images.push(a);
preloader.add(a)}}},moveFX:function(a){for(var b=zoomBook.currentPage*1-zoomBook.prevPageBuffer;b<=zoomBook.currentPage*1+zoomBook.nextPageBuffer;b++)if(b>0&&b<=bookData.pageCount){if(el.id("canvas"+b)){var c=el.id("canvas"+b),d=(b-zoomBook.currentPage-a*1)*zoomBook.pageAreaWidth;c.style.webkitTransitionDuration=zoomBook.slideSpeed+"ms";c.style.webkitTransform="translate3d("+d+"px, 0px, 0px)"}this.adjustmentFX()}},adjustmentFX:function(){this.translateScrollX=this.translateScrollY=0;var a=el.id("zoomBook");
a.style.webkitTransitionDuration=zoomBook.slideSpeed+"ms";a.style.webkitTransform="translate3d("+-this.translateScrollX+"px,"+-this.translateScrollY+"px,0px)"},next:function(){if(zoomBook.currentPage<bookData.pageCount&&timer.check("fx")){zoomBook.moveFX(1);zoomBook.currentPage++;pager.change();var a=function(){var b=zoomBook.currentPage-zoomBook.prevPageBuffer-1;el.id("canvas"+b)&&el.del("canvas"+b);images.deleteImageFromStack(b);preloader.deletePreloader(b);delete a;zoomBook.drawPage(zoomBook.currentPage*
1+zoomBook.nextPageBuffer)};window.setTimeout(a,zoomBook.slideSpeed);timer.setBlockTime(zoomBook.slideSpeed/2,zoomBook.slideSpeed)}},prev:function(){if(zoomBook.currentPage>1&&timer.check("fx")){zoomBook.moveFX(-1);zoomBook.currentPage--;pager.change();var a=function(){var b=zoomBook.currentPage*1+zoomBook.nextPageBuffer*1+1;el.id("canvas"+b)&&el.del("canvas"+b);images.deleteImageFromStack(b);preloader.deletePreloader(b);delete a;zoomBook.drawPage(zoomBook.currentPage*1-zoomBook.prevPageBuffer)};
window.setTimeout(a,zoomBook.slideSpeed);timer.setBlockTime(zoomBook.slideSpeed/2,zoomBook.slideSpeed)}},destroy:function(){preloader.stopAll();el.del("zoomBook")},goToPage:function(a){if(a<0)a=1;else if(a>bookData.pageCount)a=bookData.pageCount;if(a==zoomBook.currentPage)pageMediator.change();else if(a==zoomBook.currentPage*1+1)zoomBook.next();else if(a==zoomBook.currentPage*1-1)zoomBook.prev();else if(a>0&&a<=bookData.pageCount&&timer.check("fx")){if(a*1>zoomBook.currentPage*1){var b=zoomBook.currentPage*
1+1,c=el.id("canvas"+b).getContext("2d");b=null;c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);preloader.add(zoomBook.currentPage*1+1);preloader.setSpecial(zoomBook.currentPage*1+1);zoomBook.moveFX(1)}else{b=zoomBook.currentPage*1-1;c=el.id("canvas"+b).getContext("2d");b=null;c.fillStyle="rgb(255,255,255)";c.fillRect(0,0,zoomBook.pageWidth,zoomBook.pageHeight);preloader.add(zoomBook.currentPage*1-1);preloader.setSpecial(zoomBook.currentPage*1-1);zoomBook.moveFX(-1)}zoomBook.currentPage=
a;pager.change();var d=function(){zoomBook.destroy();zoomBook.draw(a,zoomBook.zoomFactor,zoomBook.sourcePageWidth,zoomBook.sourcePageHeight);zoomBook.adjustmentFX();delete d};c=null;window.setTimeout(d,zoomBook.slideSpeed)}},scroll:function(a,b){if(this.horizontalScroll)if(this.translateScrollX-a>this.pageWidth-device.width()){var c=this.pageWidth-device.width()-this.translateScrollX;a=-(c-(a+c)/2)}else{if(this.translateScrollX-a<0)a=this.translateScrollX*1-(this.translateScrollX*1-a)/3}else a=0;
if(this.verticalScroll)if(this.translateScrollY-b>this.pageHeight-device.height()){c=this.pageHeight-device.height()-this.translateScrollY;b=-(c-(b+c)/2)}else{if(this.translateScrollY-b<0)b=this.translateScrollY*1-(this.translateScrollY*1-b)/3}else b=0;c=el.id("zoomBook");c.style.webkitTransitionDuration="0ms";c.style.webkitTransform="translate3d("+(-this.translateScrollX*1+a*1)+"px,"+(-this.translateScrollY*1+b*1)+"px,0px)"},scrollEnd:function(a,b){var c=this.horizontalScroll?device.name()=="iPad"?
-300:-125:device.name()=="iPad"?-130:-50;if(this.translateScrollX-a>this.pageWidth-device.width()&&a<c&&this.currentPage!=bookData.pageCount)this.next();else if(this.translateScrollX-a<0&&this.currentPage!=1&&this.translateScrollX*1-a<c)this.prev();else{if(this.verticalScroll)if(this.translateScrollY-b>this.pageHeight-device.height())this.translateScrollY=this.pageHeight-device.height();else if(this.translateScrollY-b<0)this.translateScrollY=0;else this.translateScrollY-=b;if(this.horizontalScroll)if(this.translateScrollX-
a>this.pageWidth-device.width())this.translateScrollX=this.pageWidth-device.width();else if(this.translateScrollX-a<0)this.translateScrollX=0;else this.translateScrollX-=a;c=el.id("zoomBook");c.style.webkitTransitionDuration="300ms";c.style.webkitTransform="translate3d("+-this.translateScrollX+"px,"+-this.translateScrollY+"px,0px)"}maxDeltaX=null},zoomOut:function(){if(orientationObserver.getOrientation()=="portrait"){if(bookData.size.proportions<device.proportions()){onePageBook.bookHeight=(device.height()-
50).toFixed(0);onePageBook.bookWidth=(onePageBook.bookHeight*bookData.size.proportions).toFixed(0)}else{onePageBook.bookWidth=device.width()-50;onePageBook.bookHeight=(onePageBook.bookWidth/bookData.size.proportions).toFixed(0)}var a=onePageBook.bookWidth/zoomBook.pageWidth,b=zoomBook.verticalScroll?(zoomBook.pageHeight-device.height())/2:0,c=zoomBook.horizontalScroll?(zoomBook.pageWidth-device.width())/2:0;zoomEl=el.id("canvas"+zoomBook.currentPage);el.id("zoomBook").style.webkitTransitionDuration=
"150ms";el.id("zoomBook").style.webkitTransform="translate3d("+-c+"px,"+-b+"px,0px)";zoomEl.style.webkitTransitionDuration=zoomBook.zoomIOSpeed+"ms";zoomEl.style.webkitTransform="scale3d("+a+","+a+",1)";var d=function(){zoomBook.destroy();zoomBook.installed=false;onePageBook.draw(zoomBook.currentPage);delete d};b=c=a=null;window.setTimeout(d,zoomBook.zoomIOSpeed+50)}else{if(bookData.size.proportions*2<device.proportions()){twoPageBook.bookWidth=((device.height()-150)*bookData.size.proportions*2).toFixed(0);
twoPageBook.bookHeight=(device.height()-150).toFixed(0)}else{twoPageBook.bookWidth=device.width()-150;twoPageBook.bookHeight=((device.width()-150)/(bookData.size.proportions*2)).toFixed(0)}a=twoPageBook.bookWidth/2/zoomBook.pageWidth;b=zoomBook.verticalScroll?(zoomBook.pageHeight-device.height())/2:0;c=zoomBook.horizontalScroll?(zoomBook.pageWidth-device.width())/2:0;if(zoomBook.currentPage%2==0)c+=twoPageBook.bookWidth/4;else c-=twoPageBook.bookWidth/4;zoomEl=el.id("canvas"+zoomBook.currentPage);
zoomBook.destroyOtherPages();el.id("zoomBook").style.webkitTransitionDuration="150ms";el.id("zoomBook").style.webkitTransform="translate3d("+-c+"px,"+-b+"px,0px)";zoomEl.style.webkitTransitionDuration=zoomBook.zoomIOSpeed+"ms";zoomEl.style.webkitTransform="scale3d("+a+","+a+",1)";d=function(){zoomBook.destroy();zoomBook.installed=false;twoPageBook.draw(zoomBook.currentPage);delete d};window.setTimeout(d,zoomBook.zoomIOSpeed+50);b=c=a=null}},destroyOtherPages:function(){for(var a=zoomBook.currentPage*
1+zoomBook.nextPageBuffer*1,b=zoomBook.currentPage-zoomBook.prevPageBuffer;b<=a;b++)b!=zoomBook.currentPage&&b>0&&b<=bookData.pageCount&&el.del("canvas"+b)}};
zoomBook.events={tapCount:0,clickCount:0,doubleTapTime:250,doubleClickTime:250,leftAndRightArea:0.15,touchStart:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},touchMove:function(a){var b=a.targetTouches[0].pageX-eventManager.touchStartCoordinate.x,c=a.targetTouches[0].pageY-eventManager.touchStartCoordinate.y;if(links.isLinkBool&&(Math.abs(b)>2||Math.abs(c)>2))links.clearRect();zoomBook.scroll(b,c);delete a},touchEnd:function(a){Math.abs(eventManager.touchStartCoordinate.x-a.changedTouches[0].pageX)>
2||Math.abs(eventManager.touchStartCoordinate.y-a.changedTouches[0].pageY)>2?zoomBook.scrollEnd(a.changedTouches[0].pageX-eventManager.touchStartCoordinate.x,a.changedTouches[0].pageY-eventManager.touchStartCoordinate.y):zoomBook.events.touchManger(a)},mousedown:function(a){a.target.tagName=="CANVAS"&&links.drawRect(a);delete a},mousemove:function(a){var b=a.pageX-eventManager.clickStartCoordinate.x,c=a.pageY-eventManager.clickStartCoordinate.y;if(links.isLinkBool&&(Math.abs(b)>2||Math.abs(c)>2))links.clearRect();
zoomBook.scroll(b,c);delete a},mouseup:function(a){Math.abs(eventManager.clickStartCoordinate.x-a.pageX)>2||Math.abs(eventManager.clickStartCoordinate.y-a.pageY)>2?zoomBook.scrollEnd(a.pageX-eventManager.clickStartCoordinate.x,a.pageY-eventManager.clickStartCoordinate.y):zoomBook.events.clickManger(a)},touchManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs){for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b]);b=null}}else{zoomBook.events.tapCount++;
if(zoomBook.events.tapCount==1){var c=function(){if(zoomBook.events.tapCount==1){zoomBook.events.singleTap(a);zoomBook.events.tapCount=0}delete c};window.setTimeout(c,zoomBook.events.doubleTapTime)}else{zoomBook.events.doubleTap(a);zoomBook.events.tapCount=0}}},clickManger:function(a){if(links.isLinkBool&&links.currURLs){links.clearRect();if(links.currURLs)for(var b=0;b<links.currURLs.length;b++)window.open(links.currURLs[b])}else{zoomBook.events.clickCount++;if(zoomBook.events.clickCount==1){var c=
function(){if(zoomBook.events.clickCount==1){zoomBook.events.singleClick(a);zoomBook.events.clickCount=0}delete c};window.setTimeout(c,zoomBook.events.doubleClickTime)}else{zoomBook.events.doubleClick(a);zoomBook.events.clickCount=0}}},singleTap:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&zoomBook.goToPage(links.currGoPage)}else if(a.changedTouches[0].pageX<device.width()*zoomBook.events.leftAndRightArea)zoomBook.prev();else a.changedTouches[0].pageX>device.width()-device.width()*
zoomBook.events.leftAndRightArea?zoomBook.next():toolbar.toogle();delete a},doubleTap:function(){links.isLinkBool&&links.clearRect();zoomBook.zoomOut()},singleClick:function(a){if(links.isLinkBool){links.clearRect();links.currGoPage&&zoomBook.goToPage(links.currGoPage)}else if(a.x<device.width()*twoPageBook.events.leftAndRightArea)zoomBook.prev();else a.x>device.width()-device.width()*twoPageBook.events.leftAndRightArea?zoomBook.next():toolbar.toogle();delete a},doubleClick:function(a){links.isLinkBool&&
links.clearRect();zoomBook.zoomOut(a)},flipLeft:function(){zoomBook.next()},flipRight:function(){zoomBook.prev()}};
